import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header(){
  return (
    <header>
      <nav className="flex flex-1 gap-2">
        <Link href="/" className="bg-gray-400 p-2">Snowtooth Mountain</Link>
        <Link href="/mountain" className="bg-gray-400 p-2">Mountain info</Link>
      </nav>
    </header>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
